// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HideDivStageController from "./hide_div_stage_controller"
application.register("hide-div-stage", HideDivStageController)

import InterviewsController from "./interviews_controller"
application.register("interviews", InterviewsController)

import TeamSelectorController from "./team_selector_controller"
application.register("team-selector", TeamSelectorController)
